### ISSUE TITLE
App Displays White Screen

### ISSUE THREAD

**Issue by MetalNeo** [Panjkrc/ruqqus-android-app#1]
Launching the app only displays a white screen for me.

Model: Oneplus 5
OS Version: LineageOS 16 MicroG Build

**Comment by Panjkrc** [comment]
Try to install Google Webview, it seems like LineageOS doesn't come with it:
https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en

**Comment by MetalNeo** [comment]
Still just a white screen. Are there any other Google-specific dependencies required? I've disabled/removed most of the built-in ones on my device.

**Comment by Panjkrc** [comment]
Try to go to Developer Options and swap out the WebView-Implementation

**Comment by theoden8** [comment]
I'm using Android System WebView on AEX, it works.

**Comment by Panjkrc** [comment]
@MetalNeo did you resolve your issue?

**Comment by MetalNeo** [comment]
Yes, there was a placeholder WebView selected. I changed the default and now the app is displaying correctly.
