### ISSUE TITLE
Cloudflare protection is blocking app from entering

### ISSUE THREAD

**Issue by augustomen** [Panjkrc/ruqqus-android-app#13]
The newly implemented cloudflare bot protection is preventing the app from entering. The message is "Checking your browser before accessing ruqqus.com". Every 5 seconds the Ray ID changes.

I am using Android 11 with Brave browser, if that matters. I can pass the bot protection from the browser itself.

**Comment by Panjkrc** [comment]
Thanks for letting me know, I fixed it. Pushing a new update now
