### ISSUE TITLE
does't save dark mode

### ISSUE THREAD

**Issue by RedstonekPL** [Panjkrc/ruqqus-android-app#3]
When I turn on dark mode and I change the tab it goes back to light mode

![20200624_101834](https://user-images.githubusercontent.com/29150618/85521145-1fed6f00-b604-11ea-88a7-00f240a41591.gif)

**Comment by Panjkrc** [comment]
Weird, does it save dark mode in browser like chrome?

**Comment by RedstonekPL** [comment]
yes

**Comment by Panjkrc** [comment]
Try this:
Switch to dark mode, wait 5 seconds, then change tab

Let me know if it works when you do it that way

**Comment by RedstonekPL** [comment]
it didn't work too

**Comment by Panjkrc** [comment]
Are you sure you have the latest version of the app from Google Play?
https://play.google.com/store/apps/details?id=com.ruqqus

**Comment by RedstonekPL** [comment]
yes

**Comment by Panjkrc** [comment]
Did you download app from GitHub and then just updated it from Google Play once it was released there?
In that case try to uninstall app and reinstall it from Google Play

**Comment by RedstonekPL** [comment]
I downloaded the app straight from the Google Play
I also updated the app again
and uh... it started to work again now

thank you!
