### ISSUE TITLE
Footer blocks "back/next" options at the bottom of the feed

### ISSUE THREAD

**Issue by Bukenberger** [Panjkrc/ruqqus-android-app#5]
If you are using the Android app, if you are scrolled to the bottom of a feed and can see "Back/Next", it will be blocked by the footer if you view the comments on a post, and press the back button.

### Steps to reproduce:

* Go to any feed (New, Hot, etc)
* Scroll to the bottom of the feed
* View a comment section
* Press the back button

If you scroll up slightly, I believe the footer will hide, but from a UI/UX perspective the user shouldn't need to do that.

![What it looks like](https://user-images.githubusercontent.com/26699276/86501317-ca346780-bd65-11ea-850f-618147d36e74.jpg)

**Comment by Panjkrc** [comment]
Does the same happen when you go to ruqqus.com in phone browser like Chrome?

**Comment by Bukenberger** [comment]
Yes, it looks like their site does it as well

**Comment by Panjkrc** [comment]
So it's problem with ruqqus itself. Please report it under [](https://github.com/ruqqus/ruqqus/issues)
