### ISSUE TITLE
This 1 pixel triggers me... 

### ISSUE THREAD

**Issue by oicitrapdraz** [Panjkrc/ruqqus-android-app#6]
There is like `1px` of separation between the navbar and the trending bar which triggers me 😆 

![Screenshot_20200725_024239](https://user-images.githubusercontent.com/11054478/88451020-7fb48100-ce21-11ea-83a9-78591a714deb.jpg)

**Comment by Panjkrc** [comment]
Is like that in the browser also?

**Comment by oicitrapdraz** [comment]
> Is like that in the browser also?

In the browser it doesn't happen to me, even when I narrow it down to make it look like your app.

**Comment by Panjkrc** [comment]
I have no idea why is it like that. The app is just a webview so it should be the same as website

**Comment by oicitrapdraz** [comment]
> I have no idea why is it like that. The app is just a webview so it should be the same as website

Uhm, ok

**Comment by Panjkrc** [comment]
It's not like that on any of the devices I tested
