### ISSUE TITLE
(improvement) RuqES implementation

### ISSUE THREAD

**Issue by minusfourty** [Panjkrc/ruqqus-android-app#7]
Please implement some or all of the features from the Ruqqus Enhancement Suite, such as infinite scrolling, image uploading, or easier to press upvote buttons. If you could find a way to inject the RuqES userscript into the site, that'd be great.

**Comment by Panjkrc** [comment]
I tried implementing RuqES or Ruqqus Plus completly into the app but was unable to do it, will look into this a bit more
