### ISSUE TITLE
White screen error on opening

### ISSUE THREAD

**Issue by ImNotDeleted** [Panjkrc/ruqqus-android-app#8]
On opening I get this:

> Service Unavailable
> Error code: -11 
> Error description: net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH 
> FailingURL: https://ruqqus.com/

Google Pixel 3XL, Android 10
>

**Comment by Panjkrc** [comment]
Go to phone settings > apps > ruqqus, and clear app cache.

**Comment by ImNotDeleted** [comment]
Didn't work. Same issue.

**Comment by ImNotDeleted** [comment]
Oh my gosh. I think it's "parental control" settings on my router blocking it. Using a VPN gets rid of the error.

**Comment by ImNotDeleted** [comment]
Yep, this must be what it is. It works on my mobile data.
